### ISSUE TITLE
Ubuntu 22 breaks support for running App Images 

### ISSUE THREAD

**Issue by jgresham** [jgresham/nice-node#31]
## Problem details

Installing a dependency using the terminal is required to run an App Image on Ubuntu 22. See: https://askubuntu.com/questions/1403811/appimage-on-ubuntu-22-04

NiceNode should use Ubuntu's recommended format for app installation, which appears to be using Snapcraft https://ubuntu.com/desktop/developers

More info on Snap and electron apps:
https://snapcraft.io/#electron
https://www.electron.build/configuration/snap

**Comment by corn-potage** [comment]
Sorry, I thought I'd be able to give this a try, but it might be better if somebody else more familiar with build related stuff takes this on

**Comment by jgresham** [comment]
switching to `.deb` by default, but will also build `AppImage` and `snap`. Will try to publish to snap store in future. 

Future linux build targets could include any of the following supported by electron build https://www.electron.build/configuration/linux#linuxtarget
