### ISSUE TITLE
Frequently Asked Questions (FAQ) page for nicenode.xyz

### ISSUE THREAD

**Issue by jgresham** [jgresham/nice-node#33]
## Feature details

- [x] Gather question and answers from [Twitter](https://twitter.com/SirJohnsGresham/status/1519674811512811520?s=20&t=jzZkIoi-QdCEy1hZPzk8GQ), [Reddit Post 1](https://www.reddit.com/r/ethereum/comments/udw6ht/running_a_node_should_be_easier_so_i_built/), [Reddit Post 2](https://www.reddit.com/r/ethfinance/comments/udvxuq/running_a_node_should_be_easier_so_i_built/), and [Discord](https://discord.gg/htck93Aq)
- [ ] Make the answers concise and find any valuable links to include in the answers.
- [ ] Have @jgresham review them
- [ ] In a Pull Request, add them to the FAQ page at https://github.com/jgresham/nice-node-docs/blob/main/src/pages/faq/index.tsx
- [ ] Ensure that the FAQs will be formatted with when people use Search Engines (ex. Google https://developers.google.com/search/docs/advanced/structured-data/faqpage).
- [ ] Only Google support required, however, see if DuckDuckGo or Brave Search uses a similar format.

**Comment by corn-potage** [comment]
If somebody else wants to compile the questions/answers, I'd be glad to put the compiled info in the FAQ page! I'll need some time to fully understand the Search Engine stuff, but it doesn't look too difficult..

if somebody else wants to handle both at the same time, that's cool too!

**Comment by jgresham** [comment]
@corn-potage has compiled Q&A's and a working document for this has been established at https://www.notion.so/nicenode/FAQ-32f26dd6c4064dc8a6f1cc8975bcbe88
